language: java
dist: focal
jdk: openjdk11
env:
  global:
    # Check updates here: https://developer.android.com/studio/#command-tools
    # Taken from https://github.com/johnjohndoe/CampFahrplan/blob/master/.travis.yml
  - COMMAND_LINE_TOOLS_VERSION=7583922
  - ANDROID_HOME=$HOME/android-sdk
  - ANDROID_CLI_DIR=$HOME/android-tools
  - ANDROID_CLI_ZIP=${ANDROID_CLI_DIR}/commandlinetools-${COMMAND_LINE_TOOLS_VERSION}.zip
  - TARGET_SDK_VERSION=29
  - BUILD_TOOLS_VERSION=30.0.2

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - ${ANDROID_CLI_DIR}
    - ${ANDROID_HOME}
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

install:
  - mkdir -p ${ANDROID_CLI_DIR}
  - if test ! -e ${ANDROID_CLI_ZIP} ; then curl "https://dl.google.com/android/repository/commandlinetools-linux-${COMMAND_LINE_TOOLS_VERSION}_latest.zip" > ${ANDROID_CLI_ZIP} ; fi
  - unzip -qq -n ${ANDROID_CLI_ZIP} -d ${ANDROID_CLI_DIR}
  - yes | ${ANDROID_CLI_DIR}/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools"
  - yes | ${ANDROID_CLI_DIR}/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${BUILD_TOOLS_VERSION}"
  - yes | ${ANDROID_CLI_DIR}/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${TARGET_SDK_VERSION}"

before_script:
  - echo TARGET_SDK_VERSION=$TARGET_SDK_VERSION
  - echo BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION
  - chmod +x gradlew

script:
  - ./gradlew clean build --stacktrace
